# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: hzSomthing
email: hedzrz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hedzr13
github_username:  hedzr

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/logo.png
# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/favicon.png


# remote_theme: erlzhang/jekyll-theme-arktos
#remote-theme: ngzhio/jekyll-theme-hamilton
#remote_theme: thelehhman/texture

# Build settings
#theme: jekyll-theme-arktos
#theme: jekyll-theme-tactile
# https://pages-themes.github.io/tactile/
# https://github.com/pages-themes/tactile
#theme: jekyll-theme-hamilton
#theme: minima
#theme: space
#theme: texture
#theme: texture
#theme: panthera-jekyll
theme: minima
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

texture:
  style: black
  title: hz
  tagline: Developer #. Designer
  date_format: "%b %-d, %Y"
  analytics_id: UA-171624977-1
  social_links:
    twitter: hedzr13
    github:  hedzr
    #linkedIn: in/thelehhman # format: locale/username
  show_excerpts: true
  showPicker: true
  #disqus_shortname: games
  showNav: true
  navigation:
    - title: MkDocsBlog
      url: "/blog/"
    - title: MkDocsTmpl
      url: "/notes-hi/"

navigation:
  - name: 首页
    url: /
  - name: MkDocsBlog
    url: /blog/
  - name: MkDocsTmpl
    url: /notes-hi/
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags


# 每页的文章数
paginate: 8

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  #weibo: frommidworld #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: hedzrz@gmail.com 
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: hedzr/hedzr.github.io #https://github.com/<>
  instagram: #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>

# 站点页脚的文字
footer-text: Copyright &copy; 2020 Hedzr Studio

#
# 评论，注意，请不要同时添加多种不同的评论区
#

# 输入Disqus shortname，即可添加评论区
#disqus: loffer #shortname

# 输入Gitalk相关设定，即可添加评论区，具体请看教程
gitalk:
  clientID: 
  clientSecret: 
  repo: 
  owner: 

# 输入Google Analytics web tracking code
google_analytics:


#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
#version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed



# biz: https://vvalchev.github.io/creative-theme-jekyll-new/
# shop: https://stackbit-theme-planty.netlify.app/#/



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - LOFFER
